### ISSUE TITLE
Multipart form submits will break in browsers that don't implement FormData

### ISSUE THREAD

**Issue by mislav** [josh/async-form-element#13]
In browsers that support `is=async-form` but don't implement FormData, such as IE 9, trying to submit an async form will `preventDefault()` on the native "submit" event but will error out trying to serialize form using FormData and in the end no form submission will happen…

…I think. I'm guessing; I haven't actually tested this hypothesis.

Ref. 9e6db922706c7e49a18ccf0ee0f0d77004d77177

Async forms should degrade gracefully when it's not possible to submit them async.

/cc @dgraham

**Comment by josh** [comment]
Putting this repo on hold.
